### PR TITLE
Use ActiveRecord::Result API to avoid ActiveRecord deprecation warning 

### PR DESCRIPTION
**Pull request by ssnickolay**
Related to https://github.com/rails/rails/pull/33912/files

### CODE REVIEW

**Comment by ankane** [comment]
Hey @ssnickolay, thanks for the PR! I think we can turn all the `exec_query` calls into `select_all` so a separate method isn't needed.

**Comment by ssnickolay** [comment]
```ruby
[3] pry(main)> ActiveRecord::Base.connection.exec_query('SELECT 1').first
  SQL (0.8ms)  SELECT 1
=> {"1"=>1}
[4] pry(main)> ActiveRecord::Base.connection.exec_query('SELECT 1').to_a.first
  SQL (1.6ms)  SELECT 1
=> {"1"=>1}
[5] pry(main)> ActiveRecord::Base.connection.exec_query('SELECT 1').any?
  SQL (0.4ms)  SELECT 1
=> true
[6] pry(main)> ActiveRecord::Base.connection.exec_query('SELECT 1').to_a.any?
  SQL (0.8ms)  SELECT 1
=> true
```

Sounds good :+1:
@ankane do you prefer to keep `exec_query` (not `select_all`) ?

**Comment by ankane** [comment]
Let's go with `select_all` to make it consistent with Postgres.

**Comment by ssnickolay** [comment]
@ankane done 👍 I have tested on my project and everything works great

**Comment by ankane** [comment]
Looks great, thanks @ssnickolay!

**Comment by rahul342** [comment]
@ankane curious, when a new release goes out for this change. I can always reference `master`, but would be great to avoid that.
Thanks for maintaining this gem!

**Comment by ankane** [comment]
Just pushed

**Pull request merged**
